"""empty message

Revision ID: 31ca956a8c83
Revises: c3da68976db9
Create Date: 2021-07-07 23:49:51.340243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ca956a8c83'
down_revision = 'c3da68976db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'position')
    # ### end Alembic commands ###
