"""empty message

Revision ID: 3a48250eb29e
Revises: 2be801a4a7a8
Create Date: 2021-07-01 19:09:39.910756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a48250eb29e'
down_revision = '2be801a4a7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'description')
    # ### end Alembic commands ###
