"""empty message

Revision ID: 4648243e0bf6
Revises: e0a0b072b60a
Create Date: 2021-07-02 23:04:10.517356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4648243e0bf6'
down_revision = 'e0a0b072b60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_column_id', sa.Integer(), nullable=True),
    sa.Column('to_column_id', sa.Integer(), nullable=False),
    sa.Column('epochtime', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_column_id'], ['column.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['to_column_id'], ['column.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item_transitions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_transitions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('from_column_id', sa.INTEGER(), nullable=True),
    sa.Column('to_column_id', sa.INTEGER(), nullable=False),
    sa.Column('epochtime', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['from_column_id'], ['column.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['to_column_id'], ['column.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item_transition')
    # ### end Alembic commands ###
