"""empty message

Revision ID: 7291102864af
Revises: 7b5bb1314f3b
Create Date: 2021-07-04 10:32:08.751016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7291102864af'
down_revision = '7b5bb1314f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('lanes_sorted', sa.String(length=512), nullable=True))
    op.add_column('lane', sa.Column('columns_sorted', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lane', 'columns_sorted')
    op.drop_column('board', 'lanes_sorted')
    # ### end Alembic commands ###
