"""empty message

Revision ID: abbf12f65b70
Revises: 7291102864af
Create Date: 2021-07-06 22:40:37.074557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbf12f65b70'
down_revision = '7291102864af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('public', sa.Boolean(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'public')
    # ### end Alembic commands ###
