"""empty message

Revision ID: c3da68976db9
Revises: abbf12f65b70
Create Date: 2021-07-07 11:12:31.530966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3da68976db9'
down_revision = 'abbf12f65b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item1_id', sa.Integer(), nullable=False),
    sa.Column('item2_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item1_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item2_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_relationship')
    # ### end Alembic commands ###
