"""empty message

Revision ID: e0a0b072b60a
Revises: 3a48250eb29e
Create Date: 2021-07-02 22:43:54.306590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a0b072b60a'
down_revision = '3a48250eb29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_column_id', sa.Integer(), nullable=True),
    sa.Column('to_column_id', sa.Integer(), nullable=False),
    sa.Column('epochtime', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_column_id'], ['column.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['to_column_id'], ['column.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_transitions')
    # ### end Alembic commands ###
